"""Add must_change_password column

Revision ID: a5705417729d
Revises: a8c538959042
Create Date: 2026-06-16 16:57:15.179520
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'a5705417729d'
down_revision: Union[str, None] = 'a8c538959042'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('must_change_password', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'must_change_password')
    # ### end Alembic commands ###
