"""Add missing tables

Revision ID: a8c538959042
Revises: 001
Create Date: 2026-06-16 16:40:59.670915
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'a8c538959042'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_projects', sa.Column('results', sa.JSON(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_projects', 'results')
    # ### end Alembic commands ###
